### ISSUE TITLE
Move out of beta?

### ISSUE THREAD

**Issue by felixhaeberle** [mgfagency/kirby-helpsection#12]
Hey, first of all thank you for providing such a great plugin, we're really proud to have it in use extensivly. 🙏 

So there's my question: Could we move out of beta with this plugin?
What is needed to move out of beta?

I'm asking because of composer. We're managing the plugin with composer and there we have a minimum stability level.

**Comment by seehat** [comment]
Hey @felixhaeberle, good idea. For the fact, that the plugin is stable for a large amount of time I made a stable version out of it. 

I also changed the namespace, because of rebranding our agency, see here:
https://github.com/amteich/kirby-helpsection/releases/tag/1.0.1

**Comment by felixhaeberle** [comment]
@seehat Thank you very much!
